stages:
  - test

test_backend:
  stage: test
  tags: [mypersonal-runner]
  before_script:
    - mkdir -p nginx
    - |
      cat <<EOF > .env
      OPENAI_API_KEY=$OPENAI_API_KEY
      EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
      SECRET_KEY=$SECRET_KEY
      PASSWORDDB=$PASSWORDDB
      API_TOKEN=$API_TOKEN
      SECRET_API_TOKEN=$SECRET_API_TOKEN
      EOF
    - ls -la nginx/
  script:
   - docker-compose down -v  
   - docker-compose build --no-cache  
   - docker-compose up -d  
   - docker-compose exec backend python manage.py makemigrations
   - docker-compose exec backend python manage.py migrate
   - docker-compose exec backend python manage.py test
   - docker-compose down -v           
