stages:
  - test

test-job:
  stage: test
  tags: [mypersonal-runner]
  script:
    - echo "Проверка работы GitLab Runner"
    - echo "Этот шаг выполнится на любом Runner"
    - echo "Если вы видите этот текст - Runner работает!"