stages:
  - test

test_backend:
  stage: test
  tags: [mypersonal-runner]
  script:
    - docker-compose up -d        
    - docker-compose exec backend python manage.py test   
    - docker-compose down         
