version: "3.8"

services:
  backend:
    command: gunicorn IdeaCheack.wsgi:application --bind 0.0.0.0:8000 --timeout 3600
    build:
      context: ./Backend_IdeaCheck/IdeaCheack
    container_name: django
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: IdeaCheack.settings
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: IdeaCheck
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend_IdeaCheck/IdeaCheck
      dockerfile: Dockerfile
    container_name: react
    expose:
      - "80"     # expose для внутренней сети, наружу не мапим порт
    depends_on:
      - backend

  db:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: IdeaCheck
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
