# Generated by Django 5.2.1 on 2025-08-14 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('entrepreneur', 'Предприниматель '), ('expert', 'Эксперт'), ('investor', 'Инвестор'), ('moderator', 'Модератор')], default='entrepreneur')),
                ('status', models.CharField(choices=[('standart', 'Стандарт '), ('pro', 'Про')], default='standart')),
                ('jopa', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
