# Generated by Django 5.2.1 on 2025-08-14 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BusinessIdeaCheck', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertEvaluationDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.IntegerField()),
                ('innovation', models.IntegerField()),
                ('feasibility', models.IntegerField()),
                ('scalability', models.IntegerField()),
                ('clarity', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userprofile')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusinessIdeaCheck.businessidea')),
            ],
            options={
                'unique_together': {('idea', 'expert')},
            },
        ),
    ]
