# Generated by Django 5.2.1 on 2025-08-14 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('experience', models.TextField()),
                ('project', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Проверка'), ('approved', 'Одобрен'), ('rejected', 'Откланен')], default='pending')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.userprofile')),
            ],
        ),
    ]
